Removes `@${COMMIT}` from `pre-push` script and adds `--report-unused-disable-directives`.
The `--stdin-filename` flag is not just for display purposes, it is also used to determine which rules should be run for the particular file. By including the hash at the end, the files were not being correctly detected as TypeScript and using the wrong settings. This meant that `git push` and `npm run lint` disagreed, which is particular confusing.

Workaround is to pass the filename in unchanged and update the `pre-push` script to print which commit failed linting. This is a bit awkward because it must save the output of the linter into a variable and re-print it only if linting failed, however doing so would drop color information. The `script` command apparently preserves this info, which keeps the output from degrading.

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -15,11 +15,22 @@ while read LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA; do
         cut -f 1
     )
 
-    # For each commit, lint it. Husky fails if any "untested" commands fails, so
-    # we need to `||` and save the exit code to look at it without prematurely
-    # aborting.
+    # For each commit, lint it.
     if ! echo -n "${COMMITS_TO_PUSH}" |
-        xargs -L 1 -I {} bash -c "COMMIT=\"{}\" npm run -s -- lint-commit"
+        xargs -L 1 -I {} bash -c "
+            # Use script to capture colorized and styled output to a variable.
+            OUTPUT=\$(
+                script /dev/null --quiet --return --command \\
+                    \"COMMIT=\"{}\" npm run -s -- lint-commit\"
+            )
+
+            # Print lint output with the commit hash it was linting.
+            if [ \"\${?}\" != \"0\" ]; then
+                echo \"Linting commit {} failed:\"
+                echo \"\${OUTPUT}\"
+                exit 1
+            fi
+        "
     then
         SUCCESS="false"
     fi
